function P=Repopulate(P,PopulationSize,NAF,BS,...
    ChanceOfMutation,ChanceOfBigMutation,...
    ChanceOfSingleWeightMutationIfNotBig,...
    MagnitudeOfWeightMutation,...
    CanceOfAnActFuncMutation,CanceOfInvertingTheActFunc,...
    ChanceOfANewNeuron,ChanceOfLosingANeuron)

K=length(P);

for i=K+1:PopulationSize
    P1=P{i-K};
    P2=P{i-K+1};
    
    
    
    P{i}=CreateChildren(P1,P2,NAF,BS,...
        ChanceOfMutation,ChanceOfBigMutation,...
        ChanceOfSingleWeightMutationIfNotBig,...
        MagnitudeOfWeightMutation,...
        CanceOfAnActFuncMutation,CanceOfInvertingTheActFunc,...
        ChanceOfANewNeuron,ChanceOfLosingANeuron);
end


P=P;
end